### ISSUE TITLE
[Documentation] Wrong call from Kernel Request Event

### ISSUE THREAD

**Issue by LaurentSanson** [coopTilleuls/CoopTilleulsForgotPasswordBundle#120]
**Describe the bug**
Hi guys, 

I've just discovered your bundle, awesome work!

When following the documentation and implementing it, I've came accross a wrong call on the `user_not_authenticated.md` file.

The event should call `isMainRequest` instead of `isMasterRequest`.

Cheers guys !

Laurent

**Expected behavior**
```
public function onKernelRequest(RequestEvent $event): void
    {
        if (!$event->isMainRequest() || !str_starts_with($event->getRequest()->get('_route'), 'coop_tilleuls_forgot_password')) {
            return;
        }

        // User should not be authenticated on forgot password
        $token = $this->tokenStorage->getToken();
        if (null !== $token && $token->getUser() instanceof UserInterface) {
            throw new AccessDeniedHttpException;
        }
    }
```

**Comment by vincentchalamon** [comment]
Hi @LaurentSanson,

Thanks for noticing this typo in the doc. Previously, Symfony Request object has a `isMasterRequest` method, which has been renamed to `isMainRequest`. To handle the BC, there is a trait in this bundle.

But you're right, the documentation should be up to date with the latest version of Symfony. This has been fixed in https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/pull/121
