### ISSUE TITLE
Getting a 204 without a response or any other logs

### ISSUE THREAD

**Issue by jbmsubhash** [coopTilleuls/CoopTilleulsForgotPasswordBundle#127]
**Describe the bug**
When I hit the endpoint `forgot-password/` it returns me a 204 error without any logs. There are no tokens are being created in the table.

**To Reproduce**
Installed the package and the configuration done many times. It is the same.

**Expected behavior**

**Screenshots**
packages/coop_tilleuls_forgot_password.yaml
![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/18207056/7fda3879-aa9d-4673-a9ca-c345d1c248c9)

routes/coop_tilleuls_forgot_password.yaml
![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/18207056/beef79eb-cd8a-45ba-98fd-008cd4323cbe)

Entity
![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/18207056/a59d53c5-53d1-432b-a2dd-fcc902b59bc9)

Request for an invalid email
![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/18207056/63e6619b-1dfa-44b7-9f77-f2dfa64cbc49)

Happy to provide further information if required.

**Comment by vincentchalamon** [comment]
Hi @jbmsubhash,

Glad you're using this bundle :-) But I think you're missing some important security points implemented in this bundle.

The `POST /forgot-password/` route is the first one to be called in the process. You have 2 use cases:
- you send a **valid** email address: you're supposed to create an EventListener to listen to a bundle event in order to send an email (cf. [related doc](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/docs/usage.md));
- you send an **invalid** email address: no bundle event is triggered, so your EventListener is not called here.

In both use case, we're supposed to return an **empty response**.

What if we create a token in this route, and return it? Well, this is not the purpose of this route! A validation of the user (for example, by sending him a validation link to his email address) must be done first.

Bypassing this validation will be a security issue as you're not sure of the user requesting this password renewal.

Returning the token directly from this response (after checking the user with this email exists in the database) will be a security issue too as we're providing an information such as "_hey, this user exists in my database!_".

Please follow the documentation carefully:
1. [install and configure the bundle](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/docs/index.md)
2. [use this bundle for your own usage](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/docs/usage.md)
3. [increase security by ensuring the user is not authenticated](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/docs/user_not_authenticated.md)
4. (optionnal) [configure your own manager](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/docs/use_custom_manager.md) (if you're not using Doctrine)

In addition, I highly recommend you to have a look at the [Forgot Password OWASP Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html).

**Comment by jbmsubhash** [comment]
Hi @vincentchalamon ,
Thanks very much for the explanation and that makes sense.
Mostly the issue I had was related to the create token event, where it doesn't save the token when I hit the endpoint. 
My understanding of the workflow is once I hit the endpoint, it should create a token, save it in the database, then send through the email. Even though it hasn't done any of the above it returns a 204 (which I assume is OK as per your explanation). But no error for not adding the token record to the DB.
Please let me know if you have any thoughts on this.

**Comment by vincentchalamon** [comment]
Hi @jbmsubhash,

Did you create a listener on the create token event? Can you show it please?
