### ISSUE TITLE
Extra slash in documentation normalizer.

### ISSUE THREAD

**Issue by abeal-hottomali** [coopTilleuls/CoopTilleulsForgotPasswordBundle#61]
In `\CoopTilleuls\ForgotPasswordBundle\Bridge\ApiPlatform\Serializer\DocumentationNormalizer::normalize`, line 34 is `$docs['paths']['/forgot-password/']['post'] = [`.  Shouldn't it be `$docs['paths']['/forgot-password']['post'] = [`?

**Comment by vincentchalamon** [comment]
Hi @abeal-hottomali,

The POST route is `/forgot-password/` with a slash at the end, because of the [routing declaration](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/master/Resources/config/routing.xml#L7). It might be improved, but it'll cause a BC break (that's why it hasn't been fixed ^^')

**Comment by abeal-hottomali** [comment]
Ok, makes sense, thanks.
